/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rojeworldlogin;

import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javafx.stage.StageStyle;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class RjLogin extends javax.swing.JFrame {

    /**
     * Creates new form RjLogin
     */
    public RjLogin() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        addWindowListener(getWindowAdapter());
        pack();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLoginLabel = new javax.swing.JLabel();
        jUserNameField = new javax.swing.JTextField();
        jUserNameLabel = new javax.swing.JLabel();
        jPasswordLabel = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jSubmitButton = new javax.swing.JButton();
        jClearButton = new javax.swing.JButton();
        jShowPasswordCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);

        jLoginLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLoginLabel.setText("Login");
        jLoginLabel.setAlignmentX(100.0F);
        jLoginLabel.setAlignmentY(100.0F);
        jLoginLabel.setAutoscrolls(true);
        jLoginLabel.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${extendedState}"), jLoginLabel, org.jdesktop.beansbinding.BeanProperty.create("displayedMnemonic"));
        bindingGroup.addBinding(binding);

        jUserNameField.setText("UserName");
        jUserNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jUserNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jUserNameFieldFocusLost(evt);
            }
        });

        jUserNameLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jUserNameLabel.setText("UserName");

        jPasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPasswordLabel.setText("Password");

        jPasswordField.setText("Password");
        jPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusLost(evt);
            }
        });

        jSubmitButton.setText("Submit");
        jSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitButtonActionPerformed(evt);
            }
        });

        jClearButton.setText("Clear");
        jClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearButtonActionPerformed(evt);
            }
        });

        jShowPasswordCheckBox.setText("Show Password");
        jShowPasswordCheckBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jShowPasswordCheckBoxFocusGained(evt);
            }
        });
        jShowPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowPasswordCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordLabel)
                            .addComponent(jUserNameLabel))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jShowPasswordCheckBox))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLoginLabel)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSubmitButton)
                                .addGap(36, 36, 36)))
                        .addComponent(jClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jLoginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUserNameLabel)
                    .addComponent(jUserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jShowPasswordCheckBox)
                        .addComponent(jPasswordLabel))
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSubmitButton)
                    .addComponent(jClearButton))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUserNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUserNameFieldFocusGained
      
        if(jUserNameField.getText().trim().toLowerCase().equals("username")){
            jUserNameField.setText("");
        }
    }//GEN-LAST:event_jUserNameFieldFocusGained

    private void jUserNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUserNameFieldFocusLost
       if(jUserNameField.getText().trim().equals("") || jUserNameField.getText().replaceAll("\\s+","").toLowerCase().equals("username")){
           jUserNameField.setText("UserName");
       }
    }//GEN-LAST:event_jUserNameFieldFocusLost

    private void jPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusGained
       if(jPasswordField.getText().trim().toLowerCase().equals("password")){
           jPasswordField.setText("");
           
       }
        
    }//GEN-LAST:event_jPasswordFieldFocusGained

    private void jPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusLost
      if(jPasswordField.getText().replaceAll("\\s+","").equals("") || jPasswordField.getText().replaceAll("\\s+","").toLowerCase().equals("password")){
          jPasswordField.setText("Password");
      }
              
    }//GEN-LAST:event_jPasswordFieldFocusLost

    private void jShowPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowPasswordCheckBoxActionPerformed
      
        if(jShowPasswordCheckBox.isSelected()&& jPasswordField.getText().replaceAll("\\s+","").toLowerCase().equals("password")){
        
            jPasswordField.setText("");
           // jPasswordField.setEchoChar((char)0);
        }
        else if(jShowPasswordCheckBox.isSelected() && !jPasswordField.getText().replaceAll("\\s+","").toLowerCase().equals("password")){
        
            jPasswordField.setEchoChar((char)0);
        }
        else
        {
            jPasswordField.setEchoChar('•');
        }
    }//GEN-LAST:event_jShowPasswordCheckBoxActionPerformed

    private void jShowPasswordCheckBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jShowPasswordCheckBoxFocusGained
       
        if(jPasswordField.getText().replaceAll("\\s+","").toLowerCase().equals("password")){
            jPasswordField.setText("");
        }
        
        
    }//GEN-LAST:event_jShowPasswordCheckBoxFocusGained

    private void jClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearButtonActionPerformed
        // TODO add your handling code here:
         jUserNameField.setText("");
         jPasswordField.setText("");
       
    }//GEN-LAST:event_jClearButtonActionPerformed

    private void jSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitButtonActionPerformed
        // TODO add your handling code here:
          if(jUserNameField.getText().toLowerCase().replaceAll("\\s+","").equals("username")   &&  (jPasswordField.getText().toLowerCase().replaceAll("\\s+","").equals("password") || jPasswordField.getText().replaceAll("\\s+","").equals("")))
        {
            JOptionPane.showConfirmDialog(this, "Please Enter Your User Name and Password", "Login - Message",JOptionPane.CLOSED_OPTION );
            
        }
        else  if(jUserNameField.getText().toLowerCase().replaceAll("\\s+","").equals("username"))
        {
            JOptionPane.showConfirmDialog(this, "Please Enter Your User Name", "Login - Message",JOptionPane.CLOSED_OPTION);
            jUserNameField.grabFocus();
        }
        else if(jPasswordField.getText().toLowerCase().replaceAll("\\s+","").equals("password") || jPasswordField.getText().replaceAll("\\s+","").equals("") )
        {
              JOptionPane.showConfirmDialog(this, "Please Enter Your Password", "Login - Message",JOptionPane.CLOSED_OPTION);
              jPasswordField.grabFocus();
        }
        else{
             String sql="select * from login where username = ? and password = ?";
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/employe","root" , "1234");
            
            
            PreparedStatement pstm=conn.prepareStatement(sql);
            
            pstm.setString(1, jUserNameField.getText());
            
            pstm.setString(2, new String(jPasswordField.getPassword()) );
            String d=jUserNameField.getText();
            ResultSet rs= pstm.executeQuery();
            if(rs.next())
            {
                JOptionPane.showConfirmDialog(null, "Welcome "+jUserNameField.getText(), "Login - Message", JOptionPane.PLAIN_MESSAGE);
                
                Date f=new Date(); 
                
                 
                new Logout(d,f).setVisible(true);        
                     
                dispose();
            }
            else
            {
                JOptionPane.showConfirmDialog(null, "Invalid Username or Password ", " Login - Message", JOptionPane.PLAIN_MESSAGE);
            }
            conn.close();
         }
        
            catch(Exception e)
             {
                 JOptionPane.showConfirmDialog(null, e);
             }

          
        }
    }//GEN-LAST:event_jSubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RjLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RjLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RjLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RjLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RjLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jClearButton;
    private javax.swing.JLabel jLoginLabel;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JLabel jPasswordLabel;
    private javax.swing.JCheckBox jShowPasswordCheckBox;
    private javax.swing.JButton jSubmitButton;
    private javax.swing.JTextField jUserNameField;
    private javax.swing.JLabel jUserNameLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private WindowListener getWindowAdapter() {
        return new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {//overrode to show message
                super.windowClosing(we);

                
            }

            @Override
            public void windowIconified(WindowEvent we) {
                setState(JFrame.NORMAL);
                
            } //To change body of generated methods, choose Tools | Templates.
    };

    }
}

